name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pr

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make
