name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pr

    steps:
    - uses: actions/checkout@v4

    - uses: xu-cheng/latex-action@v3
      with:
        root_file: isdm24.tex
        docker_image: ghcr.io/xu-cheng/texlive-full:20240605

    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: isdm24.pdf
